---
- name: Converge
  hosts: all
  tasks:
    - name: "install deps"
      apt:
        name:
          - git
          - python-setuptools
          - python3-six
          - python3
          - python3-pip
          - python3-dev
          - python3-venv
          - python3-setuptools
          - virtualenv
        state: present
        update_cache: yes
    - name: "Include certagent_role"
      include_role:
        name: "certagent_role"
